# this source code form is subject to the terms of the mozilla public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

## ------------------------------------------- Plugin Enable Properties
mosip.certify.integration.scan-base-package=io.mosip.certify.mock.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.data-provider-plugin=PostgresDataProviderPlugin
mosip.certify.plugin-mode=DataProvider



## --------------------------------------------DataProvider specific Certify configuration --------------------------------------------------- 
# set custom VC expiry, supports limited subset of ISO-8601 Duration format starting from days to seconds
# E.g. P21dT1h-2m3s for more information check javadoc of Duration.parse(String)
mosip.certify.data-provider-plugin.vc-expiry-duration:P730d
# Cache-Control max-age value for rendering templates
mosip.certify.rendering-template.cache-max-age-days=1
## ------------------------------------------- Plugin specific usecase properties ------------------------------------------------------------
# This property is changed from issuer-uri to did-url as all the keys will be hosted on the same did.json file and kid will be appended to it for uniqueness.
mosip.certify.data-provider-plugin.did-url=did:web:marshmelloweranda.github.io:DID:dev1
# below property to be removed in next release
mosip.certify.data-provider-plugin.rendering-template-id=5b9c2a12-810a-7388-2dc8-13ee7ad88bac
# below property to be removed in next release -- temporary workaround -> INJIWEB-1202
mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/
# maps OpenID scope to the DB query string where :id is fetched from the token's "sub" field
mosip.certify.data-provider-plugin.postgres.scope-query-mapping={\
    'DrivingLicenseCredential': 'select * from certify.applications where sub=:id',\
  }

#mosip.certify.indexed-mappings.numberOfCar=$.number_of_car
#mosip.certify.indexed-mappings.registrationDate=$.registration_date
#mosip.certify.indexed-mappings.holderName=$.holder_name

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.domain.url=https://${mosip.injicertify.landregistry.host:${mosip.injicertify.host}}
mosip.certify.identifier=http://localhost:8091
mosip.certify.authorization.url=https://esignet-mock.collab.mosip.net
mosip.certify.database.name=esignet_db
# conditionally set the SOFTHSM pin based on the setup requirements and fallback to the latter if former value is missing
mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.certify.landregistry.security.pin:${softhsm.certify.security.pin}}
# Set the key prefix for Redis cache
mosip.certify.cache.redis.key-prefix=${mosip.injicertify.landregistry.host}::
# Add Display property for the issuer
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'Cadastro Ambiental Rural',\
    'locale': 'en'\
  }\
 }

mosip.certify.key-values={\
  'latest' : {\
              'credential_issuer': '${mosip.certify.identifier}',   \
              'authorization_servers': {'${mosip.certify.authorization.url}'}, \
              'credential_endpoint': '${mosipbox.public.url}${server.servlet.path}/issuance/credential', \
              'display': {{'name': 'Department of Motor Traffic', 'locale': 'en'}},\
              'credential_configurations_supported' : { \
                 'DrivingLicenseCredential' : {\
                    'format': 'ldp_vc',\
                    'scope' : 'mock_identity_vc_ldp',\
                    'cryptographic_binding_methods_supported': {'did:jwk'},\
                    'credential_signing_alg_values_supported': {'Ed25519Signature2020'},\
                    'proof_types_supported': {'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256'}}},\
                    'credential_definition': {\
                      'type': {'VerifiableCredential','DrivingLicenseCredential'},\
                      'context': {'https://www.w3.org/2018/credentials/v1','https://mosip.github.io/inji-config/contexts/driving-license-context.json},\
                      'credentialSubject': {\
                             'sub': {'display': {'name': 'Subject Identifier', 'locale': 'en'}},\
                             'application_id': {'display': {'name': 'Application ID', 'locale': 'en'}},\
                             'medical_certificate_id': {'display': {'name': 'Medical Certificate ID', 'locale': 'en'}},\
                             'full_name': {'display': {'name': 'Full Name', 'locale': 'en'}},\
                             'email': {'display': {'name': 'Email', 'locale': 'en'}},\
                             'phone': {'display': {'name': 'Phone Number', 'locale': 'en'}},\
                             'date_of_birth': {'display': {'name': 'Date of Birth', 'locale': 'en'}},\
                             'gender': {'display': {'name': 'Gender', 'locale': 'en'}},\
                             'blood_group': {'display': {'name': 'Blood Group', 'locale': 'en'}},\
                             'doctor_name': {'display': {'name': 'Doctor Name', 'locale': 'en'}},\
                             'hospital': {'display': {'name': 'Hospital', 'locale': 'en'}},\
                             'issued_date': {'display': {'name': 'Issued Date', 'locale': 'en'}},\
                             'expiry_date': {'display': {'name': 'Expiry Date', 'locale': 'en'}},\
                             'is_fit_to_drive': {'display': {'name': 'Fit to Drive', 'locale': 'en'}},\
                             'vision': {'display': {'name': 'Vision', 'locale': 'en'}},\
                             'hearing': {'display': {'name': 'Hearing', 'locale': 'en'}},\
                             'remarks': {'display': {'name': 'Remarks', 'locale': 'en'}},\
                             'photo_url': {'display': {'name': 'Photo URL', 'locale': 'en'}},\
                             'written_test': {'display': {'name': 'Written Test Results', 'locale': 'en'}},\
                             'practical_test': {'display': {'name': 'Practical Test Results', 'locale': 'en'}},\
                             'selected_categories': {'display': {'name': 'Selected Categories', 'locale': 'en'}},\
                             'total_amount': {'display': {'name': 'Total Amount', 'locale': 'en'}},\
                             'payment_reference_id': {'display': {'name': 'Payment Reference ID', 'locale': 'en'}},\
                             'payment_transaction_id': {'display': {'name': 'Payment Transaction ID', 'locale': 'en'}},\
                             'status': {'display': {'name': 'Application Status', 'locale': 'en'}} \
                     }},\
                    'display': {{'name': 'Driving License Verifiable Credential', \
                                  'locale': 'en', \
                                  'logo': {'url': 'https://mosip.github.io/inji-config/logos/agro-vertias-logo.png','alt_text': 'a square logo of a Sunbird'},\
                                  'background_color': '#FDFAF9',\
                                  'background_image': { 'uri': 'https://mosip.github.io/inji-config/logos/agro-vertias-logo.png' }, \
                                  'text_color': '#7C4616'}},\
                    'order' : {"sub","application_id","medical_certificate_id","full_name","email","phone","date_of_birth","gender","blood_group","doctor_name","hospital","issued_date","expiry_date","isfit_to_drive","vision","hearing","remarks","photo_url","written_test","practical_test","selected_categories","total_amount","payment_reference_id","payment_transaction_id","status"}\
          }}}}